name: GMEdit release

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [exe-push]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p tmp/rivals-workshop-assistant-gmedit
    - run: rsync -a --exclude='.*' --exclude='tmp' . tmp/rivals-workshop-assistant-gmedit

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        # Required, workflow file name or ID
        workflow: package.yml
        workflow_conclusion: success
        name: exe
        path: tmp/rivals-workshop-assistant-gmedit
        repo: Rivals-Workshop-Community-Projects/rivals-workshop-assistant

    - run: ls tmp/rivals-workshop-assistant-gmedit

    - uses: papeloto/action-zip@v1
      with:
        files: tmp/
        dest: tmp/rivals-workshop-assistant.zip

    - uses: actions/upload-artifact@v1
      with:
        name: zip_preview
        path: tmp/rivals-workshop-assistant.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: "tmp/rivals-workshop-assistant.zip"
        tag_name: ${{ github.event.client_payload.tag }}


    - name: GMEdit Config Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: Rivals-Workshop-Community-Projects/GMEdit-rivals-config
        event-type: gmedit-plugin-push
        client-payload: '{"tag": "${{ github.event.client_payload.tag }}"}'
