name: GMEdit release

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [exe-push]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p tmp/rivals-workshop-assistant-gmedit
    - run: rsync -a --exclude='.*' --exclude='tmp' . tmp/rivals-workshop-assistant-gmedit

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        # Required, workflow file name or ID
        workflow: package.yml
        workflow_conclusion: success
        name: rivals_workshop_assistant.exe
        path: tmp/rivals-workshop-assistant-gmedit
        repo: Rivals-Workshop-Community-Projects/rivals-workshop-assistant

    - run: ls tmp/rivals-workshop-assistant-gmedit

    - uses: papeloto/action-zip@v1
      with:
        files: tmp/rivals-workshop-assistant-gmedit/
        dest: tmp/rivals-workshop-assistant.zip

    - uses: actions/upload-artifact@v1
      with:
        name: zip_preview
        path: tmp/rivals-workshop-assistant.zip
